import { BeforeAfterData } from '../components/BeforeAfterCard';

// Données réalistes basées sur le programme La Juste Voix
// Calculs avec taux de cotisation ~23% et impôts actuels vs réforme

export const beforeAfterData: BeforeAfterData[] = [
  // SANTÉ
  {
    metier: "Infirmier(ère) hospitalier(ère)",
    statut: "5 ans d'ancienneté",
    salaireActuelBrut: 2200,
    salaireActuelNet: 1694,
    impotActuel: 42,
    salaireActuelPostImpot: 1652,
    salaireReformeNet: 2294,
    impotReforme: 45,
    salaireReformePostImpot: 2249,
    description: "Revalorisation +600€ brut",
  },
  {
    metier: "Aide-soignant(e)",
    statut: "Temps plein",
    salaireActuelBrut: 1750,
    salaireActuelNet: 1348,
    impotActuel: 0,
    salaireActuelPostImpot: 1348,
    salaireReformeNet: 1733,
    impotReforme: 0,
    salaireReformePostImpot: 1733,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Interne en médecine",
    statut: "CHU",
    salaireActuelBrut: 1800,
    salaireActuelNet: 1386,
    impotActuel: 17,
    salaireActuelPostImpot: 1369,
    salaireReformeNet: 2156,
    impotReforme: 37,
    salaireReformePostImpot: 2119,
    description: "Revalorisation +1 000€ brut",
  },
  {
    metier: "Médecin généraliste",
    statut: "Libéral",
    salaireActuelBrut: 4500,
    salaireActuelNet: 3465,
    impotActuel: 520,
    salaireActuelPostImpot: 2945,
    salaireReformeNet: 4235,
    impotReforme: 690,
    salaireReformePostImpot: 3545,
    description: "Consultation à 50€ remboursée 100% Sécu",
  },
  {
    metier: "Sage-femme hospitalière",
    statut: "10 ans d'ancienneté",
    salaireActuelBrut: 2400,
    salaireActuelNet: 1848,
    impotActuel: 78,
    salaireActuelPostImpot: 1770,
    salaireReformeNet: 2310,
    impotReforme: 62,
    salaireReformePostImpot: 2248,
    description: "Revalorisation +600€ brut",
  },

  // ÉDUCATION
  {
    metier: "Professeur des écoles",
    statut: "Début de carrière",
    salaireActuelBrut: 2100,
    salaireActuelNet: 1617,
    impotActuel: 27,
    salaireActuelPostImpot: 1590,
    salaireReformeNet: 2002,
    impotReforme: 30,
    salaireReformePostImpot: 1972,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Professeur certifié",
    statut: "10 ans d'ancienneté",
    salaireActuelBrut: 2600,
    salaireActuelNet: 2002,
    impotActuel: 118,
    salaireActuelPostImpot: 1884,
    salaireReformeNet: 2463,
    impotReforme: 108,
    salaireReformePostImpot: 2355,
    description: "Revalorisation +600€ brut",
  },
  {
    metier: "ATSEM",
    statut: "Agent territorial",
    salaireActuelBrut: 1650,
    salaireActuelNet: 1271,
    impotActuel: 0,
    salaireActuelPostImpot: 1271,
    salaireReformeNet: 1656,
    impotReforme: 0,
    salaireReformePostImpot: 1656,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Professeur agrégé",
    statut: "15 ans d'ancienneté",
    salaireActuelBrut: 3200,
    salaireActuelNet: 2464,
    impotActuel: 235,
    salaireActuelPostImpot: 2229,
    salaireReformeNet: 3079,
    impotReforme: 245,
    salaireReformePostImpot: 2834,
    description: "Revalorisation +800€ brut",
  },

  // SÉCURITÉ & JUSTICE
  {
    metier: "Policier",
    statut: "Gardien de la paix",
    salaireActuelBrut: 2200,
    salaireActuelNet: 1694,
    impotActuel: 42,
    salaireActuelPostImpot: 1652,
    salaireReformeNet: 2079,
    impotReforme: 40,
    salaireReformePostImpot: 2039,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Gendarme",
    statut: "Sous-officier",
    salaireActuelBrut: 2300,
    salaireActuelNet: 1771,
    impotActuel: 58,
    salaireActuelPostImpot: 1713,
    salaireReformeNet: 2156,
    impotReforme: 57,
    salaireReformePostImpot: 2099,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Sapeur-pompier professionnel",
    statut: "Caporal",
    salaireActuelBrut: 2000,
    salaireActuelNet: 1540,
    impotActuel: 12,
    salaireActuelPostImpot: 1528,
    salaireReformeNet: 1925,
    impotReforme: 20,
    salaireReformePostImpot: 1905,
    description: "Revalorisation +500€ brut",
  },

  // SOCIAL
  {
    metier: "Assistant(e) social(e)",
    statut: "Fonction publique",
    salaireActuelBrut: 2000,
    salaireActuelNet: 1540,
    impotActuel: 12,
    salaireActuelPostImpot: 1528,
    salaireReformeNet: 2002,
    impotReforme: 30,
    salaireReformePostImpot: 1972,
    description: "Revalorisation +600€ brut",
  },
  {
    metier: "Éducateur spécialisé",
    statut: "Début de carrière",
    salaireActuelBrut: 1900,
    salaireActuelNet: 1463,
    impotActuel: 5,
    salaireActuelPostImpot: 1458,
    salaireReformeNet: 1925,
    impotReforme: 20,
    salaireReformePostImpot: 1905,
    description: "Revalorisation +600€ brut",
  },
  {
    metier: "Travailleur social en EHPAD",
    statut: "Aide médico-psychologique",
    salaireActuelBrut: 1700,
    salaireActuelNet: 1309,
    impotActuel: 0,
    salaireActuelPostImpot: 1309,
    salaireReformeNet: 1694,
    impotReforme: 0,
    salaireReformePostImpot: 1694,
    description: "Revalorisation +500€ brut",
  },

  // PETITE ENFANCE
  {
    metier: "Auxiliaire de puériculture",
    statut: "Crèche publique",
    salaireActuelBrut: 1800,
    salaireActuelNet: 1386,
    impotActuel: 0,
    salaireActuelPostImpot: 1386,
    salaireReformeNet: 1771,
    impotReforme: 8,
    salaireReformePostImpot: 1763,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Assistante maternelle agréée",
    statut: "Travailleur indépendant",
    salaireActuelBrut: 1600,
    salaireActuelNet: 1400,
    impotActuel: 0,
    salaireActuelPostImpot: 1400,
    salaireReformeNet: 1800,
    impotReforme: 0,
    salaireReformePostImpot: 1800,
    description: "Revalorisation +400€ net",
  },

  // ADMINISTRATION
  {
    metier: "Agent administratif",
    statut: "Catégorie C - Fonction publique",
    salaireActuelBrut: 1750,
    salaireActuelNet: 1348,
    impotActuel: 0,
    salaireActuelPostImpot: 1348,
    salaireReformeNet: 1656,
    impotReforme: 0,
    salaireReformePostImpot: 1656,
    description: "Revalorisation +400€ brut",
  },

  // AGRICULTURE & ENVIRONNEMENT
  {
    metier: "Agriculteur",
    statut: "Exploitant - Revenu moyen",
    salaireActuelBrut: 1500,
    salaireActuelNet: 1500,
    impotActuel: 0,
    salaireActuelPostImpot: 1500,
    salaireReformeNet: 1800,
    impotReforme: 0,
    salaireReformePostImpot: 1800,
    description: "Soutien agricole +300€ net",
  },
  {
    metier: "Agent d'entretien des espaces verts",
    statut: "Collectivité territoriale",
    salaireActuelBrut: 1700,
    salaireActuelNet: 1309,
    impotActuel: 0,
    salaireActuelPostImpot: 1309,
    salaireReformeNet: 1617,
    impotReforme: 0,
    salaireReformePostImpot: 1617,
    description: "Revalorisation +400€ brut",
  },

  // CULTURE
  {
    metier: "Bibliothécaire",
    statut: "Fonction publique territoriale",
    salaireActuelBrut: 2000,
    salaireActuelNet: 1540,
    impotActuel: 12,
    salaireActuelPostImpot: 1528,
    salaireReformeNet: 1848,
    impotReforme: 18,
    salaireReformePostImpot: 1830,
    description: "Revalorisation +400€ brut",
  },
];
