import { BeforeAfterData } from '../components/BeforeAfterCard';

// Données réalistes basées sur le programme La Juste Voix
// Calculs avec taux de cotisation ~23% et impôts actuels vs réforme

export const beforeAfterData: BeforeAfterData[] = [
  // SANTÉ
  {
    metier: "Infirmier(ère) hospitalier(ère)",
    statut: "5 ans d'ancienneté",
    salaireActuelBrut: 2200,
    salaireActuelNet: 1694,
    impotActuel: 42,
    salaireActuelPostImpot: 1652,
    salaireReformeNet: 2294,
    impotReforme: 45,
    salaireReformePostImpot: 2249,
    description: "Revalorisation +600€ brut",
  },
  {
    metier: "Aide-soignant(e)",
    statut: "Temps plein",
    salaireActuelBrut: 1750,
    salaireActuelNet: 1348,
    impotActuel: 0,
    salaireActuelPostImpot: 1348,
    salaireReformeNet: 1733,
    impotReforme: 0,
    salaireReformePostImpot: 1733,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Interne en médecine",
    statut: "CHU",
    salaireActuelBrut: 1800,
    salaireActuelNet: 1386,
    impotActuel: 17,
    salaireActuelPostImpot: 1369,
    salaireReformeNet: 2156,
    impotReforme: 37,
    salaireReformePostImpot: 2119,
    description: "Revalorisation +1 000€ brut",
  },
  {
    metier: "Médecin généraliste",
    statut: "Libéral",
    salaireActuelBrut: 4500,
    salaireActuelNet: 3465,
    impotActuel: 520,
    salaireActuelPostImpot: 2945,
    salaireReformeNet: 4235,
    impotReforme: 690,
    salaireReformePostImpot: 3545,
    description: "Consultation à 50€ remboursée 100% Sécu",
  },
  {
    metier: "Sage-femme hospitalière",
    statut: "10 ans d'ancienneté",
    salaireActuelBrut: 2400,
    salaireActuelNet: 1848,
    impotActuel: 78,
    salaireActuelPostImpot: 1770,
    salaireReformeNet: 2310,
    impotReforme: 62,
    salaireReformePostImpot: 2248,
    description: "Revalorisation +600€ brut",
  },

  // ÉDUCATION
  {
    metier: "Professeur des écoles",
    statut: "Début de carrière",
    salaireActuelBrut: 2100,
    salaireActuelNet: 1617,
    impotActuel: 27,
    salaireActuelPostImpot: 1590,
    salaireReformeNet: 2002,
    impotReforme: 30,
    salaireReformePostImpot: 1972,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Professeur certifié",
    statut: "10 ans d'ancienneté",
    salaireActuelBrut: 2600,
    salaireActuelNet: 2002,
    impotActuel: 118,
    salaireActuelPostImpot: 1884,
    salaireReformeNet: 2463,
    impotReforme: 108,
    salaireReformePostImpot: 2355,
    description: "Revalorisation +600€ brut",
  },
  {
    metier: "ATSEM",
    statut: "Agent territorial",
    salaireActuelBrut: 1650,
    salaireActuelNet: 1271,
    impotActuel: 0,
    salaireActuelPostImpot: 1271,
    salaireReformeNet: 1656,
    impotReforme: 0,
    salaireReformePostImpot: 1656,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Professeur agrégé",
    statut: "15 ans d'ancienneté",
    salaireActuelBrut: 3200,
    salaireActuelNet: 2464,
    impotActuel: 235,
    salaireActuelPostImpot: 2229,
    salaireReformeNet: 3079,
    impotReforme: 245,
    salaireReformePostImpot: 2834,
    description: "Revalorisation +800€ brut",
  },

  // SÉCURITÉ & JUSTICE
  {
    metier: "Policier",
    statut: "Gardien de la paix",
    salaireActuelBrut: 2200,
    salaireActuelNet: 1694,
    impotActuel: 42,
    salaireActuelPostImpot: 1652,
    salaireReformeNet: 2079,
    impotReforme: 40,
    salaireReformePostImpot: 2039,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Gendarme",
    statut: "Sous-officier",
    salaireActuelBrut: 2300,
    salaireActuelNet: 1771,
    impotActuel: 58,
    salaireActuelPostImpot: 1713,
    salaireReformeNet: 2156,
    impotReforme: 57,
    salaireReformePostImpot: 2099,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Sapeur-pompier professionnel",
    statut: "Caporal",
    salaireActuelBrut: 2000,
    salaireActuelNet: 1540,
    impotActuel: 12,
    salaireActuelPostImpot: 1528,
    salaireReformeNet: 1925,
    impotReforme: 20,
    salaireReformePostImpot: 1905,
    description: "Revalorisation +500€ brut",
  },

  // ÉLUS LOCAUX - RECONNAISSANCE DU MANDAT
  {
    metier: "Maire commune rurale",
    statut: "Commune <1000 habitants",
    salaireActuelBrut: 991,
    salaireActuelNet: 991,
    impotActuel: 0,
    salaireActuelPostImpot: 991,
    salaireReformeNet: 1741,
    impotReforme: 8,
    salaireReformePostImpot: 1733,
    description: "Revalorisation +750€ nets/mois",
  },
  {
    metier: "Maire commune moyenne",
    statut: "Commune 3500-5000 habitants",
    salaireActuelBrut: 2139,
    salaireActuelNet: 2139,
    impotActuel: 37,
    salaireActuelPostImpot: 2102,
    salaireReformeNet: 2889,
    impotReforme: 135,
    salaireReformePostImpot: 2754,
    description: "Revalorisation +750€ nets/mois",
  },
  {
    metier: "Maire ville moyenne",
    statut: "Commune 10000-20000 habitants",
    salaireActuelBrut: 2528,
    salaireActuelNet: 2528,
    impotActuel: 95,
    salaireActuelPostImpot: 2433,
    salaireReformeNet: 3278,
    impotReforme: 208,
    salaireReformePostImpot: 3070,
    description: "Revalorisation +750€ nets/mois",
  },
  {
    metier: "Député(e)",
    statut: "Assemblée Nationale",
    salaireActuelBrut: 7239,
    salaireActuelNet: 5820,
    impotActuel: 1220,
    salaireActuelPostImpot: 4600,
    salaireReformeNet: 7700,
    impotReforme: 2300,
    salaireReformePostImpot: 5400,
    description: "Plafonnement 10k€ nets - Présence obligatoire",
  },

  // SOCIAL
  {
    metier: "Assistant(e) social(e)",
    statut: "Fonction publique",
    salaireActuelBrut: 2000,
    salaireActuelNet: 1540,
    impotActuel: 12,
    salaireActuelPostImpot: 1528,
    salaireReformeNet: 2002,
    impotReforme: 30,
    salaireReformePostImpot: 1972,
    description: "Revalorisation +600€ brut",
  },
  {
    metier: "Éducateur spécialisé",
    statut: "Début de carrière",
    salaireActuelBrut: 1900,
    salaireActuelNet: 1463,
    impotActuel: 5,
    salaireActuelPostImpot: 1458,
    salaireReformeNet: 1925,
    impotReforme: 20,
    salaireReformePostImpot: 1905,
    description: "Revalorisation +600€ brut",
  },
  {
    metier: "Travailleur social en EHPAD",
    statut: "Aide médico-psychologique",
    salaireActuelBrut: 1700,
    salaireActuelNet: 1309,
    impotActuel: 0,
    salaireActuelPostImpot: 1309,
    salaireReformeNet: 1694,
    impotReforme: 0,
    salaireReformePostImpot: 1694,
    description: "Revalorisation +500€ brut",
  },

  // PETITE ENFANCE
  {
    metier: "Auxiliaire de puériculture",
    statut: "Crèche publique",
    salaireActuelBrut: 1800,
    salaireActuelNet: 1386,
    impotActuel: 0,
    salaireActuelPostImpot: 1386,
    salaireReformeNet: 1771,
    impotReforme: 8,
    salaireReformePostImpot: 1763,
    description: "Revalorisation +500€ brut",
  },
  {
    metier: "Assistante maternelle agréée",
    statut: "Travailleur indépendant",
    salaireActuelBrut: 1600,
    salaireActuelNet: 1400,
    impotActuel: 0,
    salaireActuelPostImpot: 1400,
    salaireReformeNet: 1800,
    impotReforme: 0,
    salaireReformePostImpot: 1800,
    description: "Revalorisation +400€ net",
  },

  // ADMINISTRATION
  {
    metier: "Agent administratif",
    statut: "Catégorie C - Fonction publique",
    salaireActuelBrut: 1750,
    salaireActuelNet: 1348,
    impotActuel: 0,
    salaireActuelPostImpot: 1348,
    salaireReformeNet: 1656,
    impotReforme: 0,
    salaireReformePostImpot: 1656,
    description: "Revalorisation +400€ brut",
  },

  // AGRICULTURE & ENVIRONNEMENT
  {
    metier: "Agriculteur",
    statut: "Exploitant - Revenu moyen",
    salaireActuelBrut: 1500,
    salaireActuelNet: 1500,
    impotActuel: 0,
    salaireActuelPostImpot: 1500,
    salaireReformeNet: 1800,
    impotReforme: 0,
    salaireReformePostImpot: 1800,
    description: "Soutien agricole +300€ net",
  },
  {
    metier: "Agent d'entretien des espaces verts",
    statut: "Collectivité territoriale",
    salaireActuelBrut: 1700,
    salaireActuelNet: 1309,
    impotActuel: 0,
    salaireActuelPostImpot: 1309,
    salaireReformeNet: 1617,
    impotReforme: 0,
    salaireReformePostImpot: 1617,
    description: "Revalorisation +400€ brut",
  },

  // CULTURE
  {
    metier: "Bibliothécaire",
    statut: "Fonction publique territoriale",
    salaireActuelBrut: 2000,
    salaireActuelNet: 1540,
    impotActuel: 12,
    salaireActuelPostImpot: 1528,
    salaireReformeNet: 1848,
    impotReforme: 18,
    salaireReformePostImpot: 1830,
    description: "Revalorisation +400€ brut",
  },

  // COMMERCE & SERVICES PRIVÉS
  {
    metier: "Caissier(ère) supermarché",
    statut: "Temps plein - CDI",
    salaireActuelBrut: 1750,
    salaireActuelNet: 1348,
    impotActuel: 0,
    salaireActuelPostImpot: 1348,
    salaireReformeNet: 1540,
    impotReforme: 0,
    salaireReformePostImpot: 1540,
    description: "Hausse SMIC +200€ brut",
  },
  {
    metier: "Vendeur(se) prêt-à-porter",
    statut: "Commerce de détail",
    salaireActuelBrut: 1900,
    salaireActuelNet: 1463,
    impotActuel: 5,
    salaireActuelPostImpot: 1458,
    salaireReformeNet: 1617,
    impotReforme: 7,
    salaireReformePostImpot: 1610,
    description: "Amélioration +200€ brut",
  },
  {
    metier: "Serveur(se) restauration",
    statut: "Temps plein avec pourboires",
    salaireActuelBrut: 2000,
    salaireActuelNet: 1540,
    impotActuel: 12,
    salaireActuelPostImpot: 1528,
    salaireReformeNet: 1694,
    impotReforme: 12,
    salaireReformePostImpot: 1682,
    description: "Revalorisation +200€ brut",
  },
  {
    metier: "Agent de sécurité",
    statut: "Secteur privé",
    salaireActuelBrut: 1900,
    salaireActuelNet: 1463,
    impotActuel: 5,
    salaireActuelPostImpot: 1458,
    salaireReformeNet: 1617,
    impotReforme: 7,
    salaireReformePostImpot: 1610,
    description: "Revalorisation +200€ brut",
  },

  // ARTISANAT & PME
  {
    metier: "Plombier indépendant",
    statut: "Artisan auto-entrepreneur",
    salaireActuelBrut: 2800,
    salaireActuelNet: 2380,
    impotActuel: 170,
    salaireActuelPostImpot: 2210,
    salaireReformeNet: 2800,
    impotReforme: 200,
    salaireReformePostImpot: 2600,
    description: "Baisse charges, nouvelle fiscalité",
  },
  {
    metier: "Boulanger-pâtissier",
    statut: "Artisan - TPE",
    salaireActuelBrut: 2500,
    salaireActuelNet: 2125,
    impotActuel: 108,
    salaireActuelPostImpot: 2017,
    salaireReformeNet: 2500,
    impotReforme: 125,
    salaireReformePostImpot: 2375,
    description: "Allègement fiscal TPE",
  },
  {
    metier: "Coiffeur(se) salarié(e)",
    statut: "CDI salon de coiffure",
    salaireActuelBrut: 1850,
    salaireActuelNet: 1425,
    impotActuel: 0,
    salaireActuelPostImpot: 1425,
    salaireReformeNet: 1579,
    impotReforme: 0,
    salaireReformePostImpot: 1579,
    description: "Revalorisation +200€ brut",
  },
  {
    metier: "Électricien BTP",
    statut: "Ouvrier qualifié",
    salaireActuelBrut: 2400,
    salaireActuelNet: 1848,
    impotActuel: 78,
    salaireActuelPostImpot: 1770,
    salaireReformeNet: 2002,
    impotReforme: 80,
    salaireReformePostImpot: 1922,
    description: "Revalorisation +200€ brut",
  },

  // CADRES SECTEUR PRIVÉ
  {
    metier: "Cadre commercial",
    statut: "PME - 5 ans d'expérience",
    salaireActuelBrut: 3500,
    salaireActuelNet: 2695,
    impotActuel: 335,
    salaireActuelPostImpot: 2360,
    salaireReformeNet: 2695,
    impotReforme: 310,
    salaireReformePostImpot: 2385,
    description: "Nouvelle fiscalité plus juste",
  },
  {
    metier: "Ingénieur informatique",
    statut: "Grande entreprise - 8 ans",
    salaireActuelBrut: 4500,
    salaireActuelNet: 3465,
    impotActuel: 520,
    salaireActuelPostImpot: 2945,
    salaireReformeNet: 3465,
    impotReforme: 490,
    salaireReformePostImpot: 2975,
    description: "Fiscalité du mérite",
  },
  {
    metier: "Responsable RH",
    statut: "Cadre confirmé",
    salaireActuelBrut: 4000,
    salaireActuelNet: 3080,
    impotActuel: 420,
    salaireActuelPostImpot: 2660,
    salaireReformeNet: 3080,
    impotReforme: 395,
    salaireReformePostImpot: 2685,
    description: "Légère baisse d'impôt",
  },
  {
    metier: "Chef de projet IT",
    statut: "Senior - 12 ans exp",
    salaireActuelBrut: 5500,
    salaireActuelNet: 4235,
    impotActuel: 770,
    salaireActuelPostImpot: 3465,
    salaireReformeNet: 4235,
    impotReforme: 800,
    salaireReformePostImpot: 3435,
    description: "Fiscalité progressive",
  },

  // CADRES SUPÉRIEURS & DIRIGEANTS
  {
    metier: "Directeur commercial",
    statut: "Grande entreprise",
    salaireActuelBrut: 8000,
    salaireActuelNet: 6160,
    impotActuel: 1420,
    salaireActuelPostImpot: 4740,
    salaireReformeNet: 6160,
    impotReforme: 1550,
    salaireReformePostImpot: 4610,
    description: "Contribution plus importante",
  },
  {
    metier: "Directeur financier",
    statut: "ETI - Comex",
    salaireActuelBrut: 10000,
    salaireActuelNet: 7700,
    impotActuel: 2020,
    salaireActuelPostImpot: 5680,
    salaireReformeNet: 7700,
    impotReforme: 2300,
    salaireReformePostImpot: 5400,
    description: "Hausse d'impôt +280€/mois",
  },
  {
    metier: "Directeur général PME",
    statut: "150 salariés",
    salaireActuelBrut: 12000,
    salaireActuelNet: 9240,
    impotActuel: 2620,
    salaireActuelPostImpot: 6620,
    salaireReformeNet: 9240,
    impotReforme: 3100,
    salaireReformePostImpot: 6140,
    description: "Hausse d'impôt +480€/mois",
  },

  // PROFESSIONS LIBÉRALES
  {
    metier: "Avocat débutant",
    statut: "Collaborateur libéral",
    salaireActuelBrut: 3500,
    salaireActuelNet: 2975,
    impotActuel: 335,
    salaireActuelPostImpot: 2640,
    salaireReformeNet: 2975,
    impotReforme: 310,
    salaireReformePostImpot: 2665,
    description: "Légère baisse d'impôt",
  },
  {
    metier: "Avocat associé",
    statut: "Cabinet renommé - 15 ans",
    salaireActuelBrut: 15000,
    salaireActuelNet: 12750,
    impotActuel: 3820,
    salaireActuelPostImpot: 8930,
    salaireReformeNet: 12750,
    impotReforme: 4800,
    salaireReformePostImpot: 7950,
    description: "Hausse d'impôt +980€/mois",
  },
  {
    metier: "Architecte indépendant",
    statut: "Libéral - 10 ans",
    salaireActuelBrut: 5000,
    salaireActuelNet: 4250,
    impotActuel: 670,
    salaireActuelPostImpot: 3580,
    salaireReformeNet: 4250,
    impotReforme: 710,
    salaireReformePostImpot: 3540,
    description: "Légère hausse d'impôt",
  },
  {
    metier: "Expert-comptable",
    statut: "Cabinet - Associé",
    salaireActuelBrut: 8500,
    salaireActuelNet: 7225,
    impotActuel: 1620,
    salaireActuelPostImpot: 5605,
    salaireReformeNet: 7225,
    impotReforme: 1850,
    salaireReformePostImpot: 5375,
    description: "Hausse d'impôt +230€/mois",
  },

  // FINANCE & HAUTS REVENUS
  {
    metier: "Trader junior",
    statut: "Banque d'investissement",
    salaireActuelBrut: 6000,
    salaireActuelNet: 4620,
    impotActuel: 920,
    salaireActuelPostImpot: 3700,
    salaireReformeNet: 4620,
    impotReforme: 1050,
    salaireReformePostImpot: 3570,
    description: "Hausse d'impôt +130€/mois",
  },
  {
    metier: "Cadre supérieur banque",
    statut: "Directeur d'agence",
    salaireActuelBrut: 9000,
    salaireActuelNet: 6930,
    impotActuel: 1720,
    salaireActuelPostImpot: 5210,
    salaireReformeNet: 6930,
    impotReforme: 2000,
    salaireReformePostImpot: 4930,
    description: "Hausse d'impôt +280€/mois",
  },
  {
    metier: "Trader confirmé",
    statut: "Grande banque - Bonus inclus",
    salaireActuelBrut: 20000,
    salaireActuelNet: 15400,
    impotActuel: 6020,
    salaireActuelPostImpot: 9380,
    salaireReformeNet: 15400,
    impotReforme: 7800,
    salaireReformePostImpot: 7600,
    description: "Hausse d'impôt +1780€/mois",
  },

  // TRÈS HAUTS REVENUS
  {
    metier: "Chirurgien libéral réputé",
    statut: "Clinique privée",
    salaireActuelBrut: 25000,
    salaireActuelNet: 21250,
    impotActuel: 8020,
    salaireActuelPostImpot: 13230,
    salaireReformeNet: 21250,
    impotReforme: 10500,
    salaireReformePostImpot: 10750,
    description: "Hausse d'impôt +2480€/mois",
  },
  {
    metier: "Directeur général CAC 40",
    statut: "Haute direction",
    salaireActuelBrut: 50000,
    salaireActuelNet: 38500,
    impotActuel: 18020,
    salaireActuelPostImpot: 20480,
    salaireReformeNet: 38500,
    impotReforme: 23500,
    salaireReformePostImpot: 15000,
    description: "Hausse d'impôt +5480€/mois",
  },
  {
    metier: "Chef d'entreprise (500 salariés)",
    statut: "Rémunération annuelle 600k€",
    salaireActuelBrut: 50000,
    salaireActuelNet: 38500,
    impotActuel: 18020,
    salaireActuelPostImpot: 20480,
    salaireReformeNet: 38500,
    impotReforme: 23500,
    salaireReformePostImpot: 15000,
    description: "Hausse d'impôt +5480€/mois",
  },

  // MILLIONNAIRES & ULTRA-RICHES (PAYEURS CNJP)
  {
    metier: "Entrepreneur millionnaire",
    statut: "Patrimoine 5M€ - Dividendes",
    salaireActuelBrut: 100000,
    salaireActuelNet: 85000,
    impotActuel: 38020,
    salaireActuelPostImpot: 46980,
    salaireReformeNet: 85000,
    impotReforme: 48000,
    salaireReformePostImpot: 37000,
    description: "Impôt +9980€/mois + Pas de CNJP (<100M€)",
  },
  {
    metier: "Héritier grande fortune",
    statut: "Patrimoine 150M€ - Rentes",
    salaireActuelBrut: 200000,
    salaireActuelNet: 170000,
    impotActuel: 78020,
    salaireActuelPostImpot: 91980,
    salaireReformeNet: 170000,
    impotReforme: 98000,
    salaireReformePostImpot: 72000,
    description: "Impôt +19980€/mois + CNJP 250k€/mois (150M€ à 2%)",
  },
  {
    metier: "Milliardaire",
    statut: "Patrimoine 2Md€ - Revenus du capital",
    salaireActuelBrut: 500000,
    salaireActuelNet: 425000,
    impotActuel: 198020,
    salaireActuelPostImpot: 226980,
    salaireReformeNet: 425000,
    impotReforme: 248000,
    salaireReformePostImpot: 177000,
    description: "Impôt +49980€/mois + CNJP 833k€/mois (2Md€ à 5%)",
  },
  {
    metier: "Ultra-riche (Top 0,01%)",
    statut: "Patrimoine 10Md€",
    salaireActuelBrut: 1000000,
    salaireActuelNet: 850000,
    impotActuel: 398020,
    salaireActuelPostImpot: 451980,
    salaireReformeNet: 850000,
    impotReforme: 498000,
    salaireReformePostImpot: 352000,
    description: "Impôt +99980€/mois + CNJP 2,5M€/mois (10Md€ à 30%)",
  },

  // RETRAITÉS
  {
    metier: "Retraité(e) carrière complète",
    statut: "Ancien cadre moyen",
    salaireActuelBrut: 2200,
    salaireActuelNet: 2090,
    impotActuel: 42,
    salaireActuelPostImpot: 2048,
    salaireReformeNet: 2200,
    impotReforme: 45,
    salaireReformePostImpot: 2155,
    description: "Protection du pouvoir d'achat",
  },
  {
    metier: "Retraité(e) modeste",
    statut: "Carrière incomplète",
    salaireActuelBrut: 1400,
    salaireActuelNet: 1330,
    impotActuel: 0,
    salaireActuelPostImpot: 1330,
    salaireReformeNet: 1500,
    impotReforme: 0,
    salaireReformePostImpot: 1500,
    description: "Revalorisation minimum vieillesse +100€",
  },

  // SITUATIONS PRÉCAIRES
  {
    metier: "Bénéficiaire RSA",
    statut: "Personne seule sans emploi",
    salaireActuelBrut: 0,
    salaireActuelNet: 607,
    impotActuel: 0,
    salaireActuelPostImpot: 607,
    salaireReformeNet: 700,
    impotReforme: 0,
    salaireReformePostImpot: 700,
    description: "Hausse RSA +93€/mois",
  },
  {
    metier: "Étudiant boursier",
    statut: "Échelon 5 + Job étudiant",
    salaireActuelBrut: 0,
    salaireActuelNet: 480,
    impotActuel: 0,
    salaireActuelPostImpot: 480,
    salaireReformeNet: 650,
    impotReforme: 0,
    salaireReformePostImpot: 650,
    description: "Hausse bourse + aide logement +170€",
  },
  {
    metier: "Apprenti CAP",
    statut: "1ère année",
    salaireActuelBrut: 477,
    salaireActuelNet: 477,
    impotActuel: 0,
    salaireActuelPostImpot: 477,
    salaireReformeNet: 700,
    impotReforme: 0,
    salaireReformePostImpot: 700,
    description: "SMIC horaire obligatoire stages +223€",
  },
];
